apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: ejercicio-00
spec:
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: almcjmi/lc-todo-monolith
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 3000
        env:
          - name: NODE_ENV
            value: production
          - name: PORT
            value: "3000"