apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-front
  namespace: ejercicio-02
spec:
  selector:
    matchLabels:
      app: todo-front
  template:
    metadata:
      labels:
        app: todo-front
    spec:
      containers:
      - name: todo-front
        image: almcjmi/lc-todo-front
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 80