apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: ejercicio-02
spec:
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: almcjmi/lc-todo-api
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
             name: todo-api-cm
